delivery:
  token:
    access_ttl: 30s
    refresh_ttl: 876000h
    signing_key: "signing_key"

  http:
    port:

storage:
  hash_type: "sha1"
  max_init_time: 5s
  type: "postgre"

  memory:
    #...

  sql:
    postgre:
      host: "127.0.0.1"
      port: 5432
      user: "postgres"
      password: "admin"
      database: "geoqq"
    sqlite:
      #...

server:
  http:
    port: 57000