server:
  http:
    host: ""
    port: 57000

    read_timeout: 10s
    write_timeout: 10s
    shutdown_timeout: 5s

  # is not http?
  websocket:

delivery:
  token:
    access_ttl: 30m
    refresh_ttl: 876000h
    signing_key: "signing_key"

storage:
  hash_type: "sha1" # general parameter?
  max_init_time: 5s

  file: # or resource/blob
    type: "anytime"
    memory:
      anytime:
          root: "."
          avatar: "avatar"
          #...
      runtime:
      #...

  domain: # or models/business
    type: "postgre"
  
    memory:
      #...

    sql:
      postgre:
        host: "127.0.0.1"
        port: 5432

        user: "postgres"
        password: "admin"
        database: "geoqq"

        background:
          query_timeout: 10s
          max_query_count: 2

      sqlite:
        #...

logging:
  type: "lumberjack"
  level: 0
  use_console: true

  lumberjack:
    dirname: "./rotation"
    filename: "server.log"

    max_size_mb: 100
    max_backups: 5
    max_age_days: 1

  mlog:
    #...
