logging:
  type: lumberjack

  name: geoqq_ws
  level: 0
  format: text # text, json
  
  use_console: true

  dirname: ./rotation/ws
  filename: server.log

  max_size_mb: 100
  max_backups: 5

  lumberjack:
    max_age_days: 1 # to disable use 0!

  mlog:
    #...

  zkits:
    #...

adapters:
  interfaces:
    ws:
      host:
      port: 57002
      max_header_kb: 1000 # http
      read_timeout: 25s
      write_timeout: 25s
      ping:
        enable: false
        timeout: 25s
      token:
        signing_key: "signing_key"

  