logging:
  type: lumberjack

  name: geoqq_ws
  level: 0
  format: text # text, json
  
  use_console: true

  dirname: ./rotation/ws
  filename: server.log

  max_size_mb: 100
  max_backups: 5

  lumberjack:
    max_age_days: 1 # to disable use 0!

  mlog:
    #...

  zkits:
    #...

adapters:
  interfaces:
    ws:
      host: "0.0.0.0"
      port: 57002
      max_header_kb: 1000 # http
      read_timeout: 25s
      write_timeout: 25s
      ping:
        enable: false
        timeout: 25s
      token:
        signing_key: "signing_key"
  
  infra:
    database:
      type: postgre
      sql:
        postgre:
          host: "127.0.0.1"
          port: 5432

          user: "postgres"
          password: "admin"
          database: "geoqq"

    cache:
      type: redis
      redis:
        host: "127.0.0.1"
        port: 6379
        
        user: ""
        password: ""
        db_index: 1



  