logging:



adapters:
  interfaces:
    ws:
      host:
      port: 57002
      max_header_kb: 1000 # http
      read_timeout: 25s
      write_timeout: 25s
      ping:
        enable: false
        timeout: 25s

  