name: geoqq_external_services

services:
  loki: 
    image: grafana/loki:latest
    hostname: ${GRAFANA_LOKI_NAME}
    container_name: ${GRAFANA_LOKI_NAME}
    ports:
      - "${EXTERNAL_GRAFANA_LOKI_PORT}:${GRAFANA_LOKI_PORT}"
    networks:
      - external_net

networks:
  external_net:
    external: true